name: CD-projeto-prod

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          rm -rf lab_eng_software
          git clone https://github.com/VitorOnoue/lab_eng_software.git
          cd lab_eng_software
          sudo cp -r frontend /var/www/html
          cd backend
          pm2 stop app.js
          pm2 start app.js
          EOF